#!/usr/bin/env node

/**
 * Fantasy Book Database Seeder
 * Inserts curated fantasy books with full metadata into Supabase.
 *
 * BEFORE RUNNING: make sure the audience column exists in Supabase:
 *   ALTER TABLE books ADD COLUMN IF NOT EXISTS audience text;
 */

import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const envContent = readFileSync(path.join(__dirname, '.env'), 'utf-8');
const env = {};
envContent.split('\n').forEach((line) => {
  const [key, ...rest] = line.split('=');
  if (key && rest.length) env[key.trim()] = rest.join('=').trim();
});

const supabaseUrl = env.PUBLIC_SUPABASE_URL;
const supabaseKey = env.PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('❌ Missing Supabase credentials in .env file');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

// Cover URLs via Open Library ISBN covers (free, no API key needed)
const cover = (isbn) => `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;

const BOOKS = [
  {
    title: 'The Name of the Wind',
    slug: 'the-name-of-the-wind',
    authors: ['Patrick Rothfuss'],
    isbn: '9780756404079',
    cover_url: cover('9780756404079'),
    publication_year: 2007,
    page_count: 662,
    avg_rating: 4.55,
    synopsis:
      'A young man grows up to become the most notorious wizard his world has ever seen. Told in his own words, this is the story of Kvothe—from his childhood in a troupe of traveling players, to years spent as a near-feral orphan in a crime-ridden city, to his daringly brazen yet successful bid to enter a legendary school of magic.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'High Fantasy'],
    tropes: ['Magic Academy', 'Chosen One', 'Coming of Age', 'Reluctant Hero'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Character-driven'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'The Way of Kings',
    slug: 'the-way-of-kings',
    authors: ['Brandon Sanderson'],
    isbn: '9780765326355',
    cover_url: cover('9780765326355'),
    publication_year: 2010,
    page_count: 1007,
    avg_rating: 4.65,
    synopsis:
      'Roshar is a world of stone and storms. Uncanny tempests of incredible power sweep across the rocky terrain so frequently that they have shaped ecology and civilization alike. Animals hide in shells, trees pull in branches, and grass retracts into the soilless ground. Cities are built only where the topography offers shelter.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'High Fantasy'],
    tropes: ['Chosen One', 'Quest', 'Political Intrigue', 'Mentor Figure'],
    magic_system: 'Hard Magic',
    tone: ['Philosophical', 'Dark & Serious', 'Action-packed'],
    pacing: 'Slow-burn',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'A Court of Thorns and Roses',
    slug: 'a-court-of-thorns-and-roses',
    authors: ['Sarah J. Maas'],
    isbn: '9781619634169',
    cover_url: cover('9781619634169'),
    publication_year: 2015,
    page_count: 419,
    avg_rating: 4.15,
    synopsis:
      'A young huntress is taken to the faerie lands after killing a wolf in the woods. There she discovers that her captor is not what he seems, and the world beyond the wall is more beautiful and more deadly than she ever imagined.',
    audience: 'Young Adult (YA)',
    subgenres: ['Romantic Fantasy', 'High Fantasy'],
    tropes: ['Fae Court Drama', 'Enemies to Lovers', 'Forbidden Romance', 'Curse Breaking'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Action-packed'],
    pacing: 'Fast-paced',
    heat_level: 'Spicy',
    diversity_rep: [],
  },
  {
    title: 'The Lies of Locke Lamora',
    slug: 'the-lies-of-locke-lamora',
    authors: ['Scott Lynch'],
    isbn: '9780553588941',
    cover_url: cover('9780553588941'),
    publication_year: 2006,
    page_count: 499,
    avg_rating: 4.30,
    synopsis:
      "An orphan's life is harsh and that's if he's lucky. Lucky Locke Lamora dodged the fates of most street kids: conscription, death, or slavery. Instead, he became a member of a thieving crew—the Gentlemen Bastards—who con the nobility of Camorr while the city's crime lord believes he's just running small-time scams.",
    audience: 'Adult',
    subgenres: ['Low Fantasy', 'Grimdark'],
    tropes: ['Heist', 'Found Family', 'Political Intrigue', 'Betrayal'],
    magic_system: 'No Magic',
    tone: ['Dark & Serious', 'Humorous', 'Action-packed'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Mistborn: The Final Empire',
    slug: 'mistborn-the-final-empire',
    authors: ['Brandon Sanderson'],
    isbn: '9780765350381',
    cover_url: cover('9780765350381'),
    publication_year: 2006,
    page_count: 541,
    avg_rating: 4.45,
    synopsis:
      'For a thousand years the ash fell and no flowers bloomed. For a thousand years the Skaa slaved in misery and lived in fear. For a thousand years the Lord Ruler reigned with absolute power and ultimate terror. The Skaa now plan a rebellion. Their only hope is the criminal Kelsier—and a young girl who might just be the most powerful Mistborn in history.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'High Fantasy'],
    tropes: ['Chosen One', 'Heist', 'Political Intrigue', 'Betrayal', 'Mentor Figure'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Action-packed', 'Hopeful'],
    pacing: 'Mixed',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'Six of Crows',
    slug: 'six-of-crows',
    authors: ['Leigh Bardugo'],
    isbn: '9781627792127',
    cover_url: cover('9781627792127'),
    publication_year: 2015,
    page_count: 465,
    avg_rating: 4.46,
    synopsis:
      'Ketterdam: a bustling hub of international trade where anything can be had for the right price—and no one knows that better than criminal prodigy Kaz Brekker. Six misfits with nothing to lose and everything to gain—their mission: to break into the most secure facility in the world.',
    audience: 'Young Adult (YA)',
    subgenres: ['Epic Fantasy', 'Low Fantasy'],
    tropes: ['Heist', 'Found Family', 'Enemies to Lovers', 'Political Intrigue'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Action-packed'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: ['POC Protagonist', 'Disability Rep'],
  },
  {
    title: 'The Hobbit',
    slug: 'the-hobbit',
    authors: ['J.R.R. Tolkien'],
    isbn: '9780547928227',
    cover_url: cover('9780547928227'),
    publication_year: 1937,
    page_count: 310,
    avg_rating: 4.28,
    synopsis:
      'Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely venturing further than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure.',
    audience: "Children's",
    subgenres: ['Epic Fantasy', 'High Fantasy'],
    tropes: ['Quest', 'Dragon Rider', 'Reluctant Hero', 'Found Family', 'Dark Lord'],
    magic_system: 'Soft Magic',
    tone: ['Whimsical', 'Light-hearted', 'Action-packed'],
    pacing: 'Mixed',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'Good Omens',
    slug: 'good-omens',
    authors: ['Terry Pratchett', 'Neil Gaiman'],
    isbn: '9780060853976',
    cover_url: cover('9780060853976'),
    publication_year: 1990,
    page_count: 288,
    avg_rating: 4.25,
    synopsis:
      'According to the Nice and Accurate Prophecies of Agnes Nutter, the world will end on a Saturday. An angel and a demon who have been on Earth since The Beginning must work together to avert Armageddon—but they rather like the world as it is.',
    audience: 'Adult',
    subgenres: ['Contemporary Fantasy', 'Urban Fantasy'],
    tropes: ['Found Family', 'Prophecy'],
    magic_system: 'Soft Magic',
    tone: ['Humorous', 'Whimsical', 'Light-hearted'],
    pacing: 'Fast-paced',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'The House in the Cerulean Sea',
    slug: 'the-house-in-the-cerulean-sea',
    authors: ['TJ Klune'],
    isbn: '9781250217318',
    cover_url: cover('9781250217318'),
    publication_year: 2020,
    page_count: 394,
    avg_rating: 4.40,
    synopsis:
      "Linus Baker is a by-the-book case worker at the Department in Charge of Magical Youth. He's sent on a secret assignment to a magical orphanage on a mysterious island, home to the most dangerous magical children ever seen—and their charming, enigmatic master.",
    audience: 'Adult',
    subgenres: ['Cozy Fantasy', 'Contemporary Fantasy'],
    tropes: ['Found Family', 'Enemies to Lovers', 'Slow Burn'],
    magic_system: 'Soft Magic',
    tone: ['Whimsical', 'Light-hearted', 'Humorous'],
    pacing: 'Slow-burn',
    heat_level: 'Fade to Black',
    diversity_rep: ['LGBTQ+ Protagonist'],
  },
  {
    title: 'Piranesi',
    slug: 'piranesi',
    authors: ['Susanna Clarke'],
    isbn: '9781635575644',
    cover_url: cover('9781635575644'),
    publication_year: 2020,
    page_count: 272,
    avg_rating: 4.20,
    synopsis:
      'Piranesi lives in the House. Perhaps he always has. In his notebooks, he makes careful observations: the House is beautiful, its rooms full of marvels. He is not afraid—though sometimes he wonders if he should be.',
    audience: 'Adult',
    subgenres: ['Contemporary Fantasy', 'Low Fantasy'],
    tropes: ['Secret Identity', 'Slow Burn'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Philosophical', 'Whimsical'],
    pacing: 'Slow-burn',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'Legends & Lattes',
    slug: 'legends-and-lattes',
    authors: ['Travis Baldree'],
    isbn: '9781250882981',
    cover_url: cover('9781250882981'),
    publication_year: 2022,
    page_count: 299,
    avg_rating: 4.10,
    synopsis:
      'After decades of adventuring, Viv the orc barbarian hangs up her sword and buys a plot of land in the city of Thune, where she plans to open the first coffee shop in a world that has never seen the drink.',
    audience: 'Adult',
    subgenres: ['Cozy Fantasy', 'Low Fantasy'],
    tropes: ['Found Family', 'Slow Burn', 'Enemies to Lovers'],
    magic_system: 'No Magic',
    tone: ['Whimsical', 'Light-hearted', 'Character-driven'],
    pacing: 'Slow-burn',
    heat_level: 'Fade to Black',
    diversity_rep: ['LGBTQ+ Protagonist', 'POC Side Characters'],
  },
  {
    title: 'Circe',
    slug: 'circe',
    authors: ['Madeline Miller'],
    isbn: '9780316556347',
    cover_url: cover('9780316556347'),
    publication_year: 2018,
    page_count: 393,
    avg_rating: 4.15,
    synopsis:
      'In the house of Helios, god of the sun and mightiest of the Titans, a daughter is born. But Circe is a strange child—neither powerful like her father nor viciously alluring like her mother. When she discovers she possesses the power of witchcraft, she is exiled to a deserted island.',
    audience: 'Adult',
    subgenres: ['Mythic Fantasy', 'Historical Fantasy'],
    tropes: ['Coming of Age', 'Curse Breaking', 'Slow Burn', 'Revenge Story'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Philosophical', 'Character-driven'],
    pacing: 'Slow-burn',
    heat_level: 'Steamy',
    diversity_rep: [],
  },
  {
    title: 'The Blade Itself',
    slug: 'the-blade-itself',
    authors: ['Joe Abercrombie'],
    isbn: '9781591025948',
    cover_url: cover('9781591025948'),
    publication_year: 2006,
    page_count: 515,
    avg_rating: 4.15,
    synopsis:
      'Logen Ninefingers, infamous barbarian, has finally run out of luck. Nobleman Captain Jezal dan Luthar trains for glory. Inquisitor Glokta, a cripple turned torturer, hopes to discover a conspiracy. Their fates are intertwined as an ancient evil stirs in the North.',
    audience: 'Adult',
    subgenres: ['Grimdark', 'Epic Fantasy'],
    tropes: ['Political Intrigue', 'Quest', 'Reluctant Hero', 'Betrayal'],
    magic_system: 'Soft Magic',
    tone: ['Grimdark', 'Dark & Serious', 'Humorous'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: ['Disability Rep'],
  },
  {
    title: 'American Gods',
    slug: 'american-gods',
    authors: ['Neil Gaiman'],
    isbn: '9780380789030',
    cover_url: cover('9780380789030'),
    publication_year: 2001,
    page_count: 465,
    avg_rating: 4.10,
    synopsis:
      'Shadow is a man who serves his prison time by picking up work where he can find it. After his release, he meets a mysterious man who calls himself Wednesday, and a storm is coming—one that will battle for the very soul of America.',
    audience: 'Adult',
    subgenres: ['Urban Fantasy', 'Mythic Fantasy', 'Contemporary Fantasy'],
    tropes: ['Quest', 'Secret Identity'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Dark & Serious', 'Philosophical'],
    pacing: 'Slow-burn',
    heat_level: 'Steamy',
    diversity_rep: [],
  },
  {
    title: 'The Night Circus',
    slug: 'the-night-circus',
    authors: ['Erin Morgenstern'],
    isbn: '9780385534635',
    cover_url: cover('9780385534635'),
    publication_year: 2011,
    page_count: 387,
    avg_rating: 4.05,
    synopsis:
      'The circus arrives without warning. No announcements precede it. It is simply there, when yesterday it was not. Two young magicians are trained from childhood to compete against each other in an arena they cannot choose to leave—a mysterious black-and-white circus that becomes an obsession for all who encounter it.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'Romantic Fantasy'],
    tropes: ['Forbidden Romance', 'Slow Burn'],
    magic_system: 'Soft Magic',
    tone: ['Whimsical', 'Atmospheric', 'Philosophical'],
    pacing: 'Slow-burn',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'The Poppy War',
    slug: 'the-poppy-war',
    authors: ['R.F. Kuang'],
    isbn: '9780062662583',
    cover_url: cover('9780062662583'),
    publication_year: 2018,
    page_count: 530,
    avg_rating: 4.10,
    synopsis:
      "When Rin aced the Keju—the Empire's test to identify the most talented young people—she was taken from her poor village to the prestigious Sinegard military academy. She discovers she has a power that could save her country—or destroy it.",
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'Grimdark', 'Dark Fantasy'],
    tropes: ['Magic Academy', 'Coming of Age', 'Chosen One', 'Revenge Story'],
    magic_system: 'Soft Magic',
    tone: ['Grimdark', 'Dark & Serious', 'Action-packed'],
    pacing: 'Mixed',
    heat_level: 'Clean',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: 'The Priory of the Orange Tree',
    slug: 'the-priory-of-the-orange-tree',
    authors: ['Samantha Shannon'],
    isbn: '9781620409435',
    cover_url: cover('9781620409435'),
    publication_year: 2019,
    page_count: 827,
    avg_rating: 4.10,
    synopsis:
      'A world divided. A dragon rising. Three women will determine the fate of everything. An epic standalone fantasy about three women on opposite sides of a religious war who must each make the choice between duty and the truth that could shatter their world.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'High Fantasy'],
    tropes: ['Dragon Rider', 'Political Intrigue', 'Quest', 'Forbidden Romance'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Atmospheric', 'Hopeful'],
    pacing: 'Slow-burn',
    heat_level: 'Fade to Black',
    diversity_rep: ['LGBTQ+ Protagonist', 'POC Protagonist'],
  },
  {
    title: 'Harry Potter and the Philosopher\'s Stone',
    slug: 'harry-potter-philosophers-stone',
    authors: ['J.K. Rowling'],
    isbn: '9780590353427',
    cover_url: cover('9780590353427'),
    publication_year: 1997,
    page_count: 223,
    avg_rating: 4.47,
    synopsis:
      'Harry Potter has never even heard of Hogwarts when the letters start arriving on his doormat. A giant of a man breaks down the door to give Harry his invitation to the most wonderful place in the world. Boarding the Hogwarts Express is the beginning of a magical adventure.',
    audience: "Children's",
    subgenres: ['High Fantasy', 'Portal Fantasy'],
    tropes: ['Magic Academy', 'Chosen One', 'Coming of Age', 'Dark Lord', 'Found Family'],
    magic_system: 'Soft Magic',
    tone: ['Whimsical', 'Light-hearted', 'Hopeful'],
    pacing: 'Mixed',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'A Deadly Education',
    slug: 'a-deadly-education',
    authors: ['Naomi Novik'],
    isbn: '9780593128480',
    cover_url: cover('9780593128480'),
    publication_year: 2020,
    page_count: 313,
    avg_rating: 4.10,
    synopsis:
      'El Higgins is at a school full of monsters—and she\'s not talking about the students. The Scholomance has no teachers, no library, and no dining hall. It just has students, trying to learn enough magic to survive before monsters kill them. El has been assigned to the most dangerous room, and the only student willing to help her is the one she hates most.',
    audience: 'Young Adult (YA)',
    subgenres: ['Dark Fantasy', 'High Fantasy'],
    tropes: ['Magic Academy', 'Enemies to Lovers', 'Slow Burn', 'Chosen One'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Humorous', 'Character-driven'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: 'An Ember in the Ashes',
    slug: 'an-ember-in-the-ashes',
    authors: ['Sabaa Tahir'],
    isbn: '9781595148049',
    cover_url: cover('9781595148049'),
    publication_year: 2015,
    page_count: 446,
    avg_rating: 4.05,
    synopsis:
      'Laia is a slave. Elias is a soldier. Neither is free. Under the Martial Empire, defiance is met with death. When Laia\'s brother is arrested for treason, she must make an unimaginable choice. In a city of mirrors and shadows, two people discover that their fates are entwined.',
    audience: 'Young Adult (YA)',
    subgenres: ['Historical Fantasy', 'Epic Fantasy', 'Romantic Fantasy'],
    tropes: ['Enemies to Lovers', 'Forbidden Romance', 'Chosen One', 'Tournament Arc', 'Political Intrigue'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Action-packed'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: ['POC Protagonist'],
  },
  // --- Batch 2 ---
  {
    title: 'A Game of Thrones',
    slug: 'a-game-of-thrones',
    authors: ['George R.R. Martin'],
    isbn: '9780553573404',
    cover_url: cover('9780553573404'),
    publication_year: 1996,
    page_count: 694,
    avg_rating: 4.44,
    synopsis:
      'Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister forces are massing. To the south, the King\'s powers are failing. At the center of the conflict lie the Starks of Winterfell, a family as harsh and unyielding as the land they were born to.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'High Fantasy', 'Grimdark'],
    tropes: ['Political Intrigue', 'Betrayal', 'Dark Lord', 'Dragons', 'Coming of Age'],
    magic_system: 'Soft Magic',
    tone: ['Grimdark', 'Dark & Serious', 'Character-driven'],
    pacing: 'Mixed',
    heat_level: 'Steamy',
    diversity_rep: [],
  },
  {
    title: 'The Fellowship of the Ring',
    slug: 'the-fellowship-of-the-ring',
    authors: ['J.R.R. Tolkien'],
    isbn: '9780618346257',
    cover_url: cover('9780618346257'),
    publication_year: 1954,
    page_count: 398,
    avg_rating: 4.36,
    synopsis:
      'One Ring to rule them all. In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring to rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost. After many ages it fell into the hands of the hobbit Bilbo Baggins. Now his young cousin Frodo must carry it on a desperate quest to the fires of Mount Doom.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'High Fantasy'],
    tropes: ['Quest', 'Dark Lord', 'Found Family', 'Chosen One', 'Reluctant Hero'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Whimsical', 'Philosophical'],
    pacing: 'Slow-burn',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'A Wizard of Earthsea',
    slug: 'a-wizard-of-earthsea',
    authors: ['Ursula K. Le Guin'],
    isbn: '9780547773742',
    cover_url: cover('9780547773742'),
    publication_year: 1968,
    page_count: 183,
    avg_rating: 4.10,
    synopsis:
      'A boy with strange powers becomes a student at a school for wizards, where his pride and impatience lead him to meddle with long-held secrets—unleashing a terrible shadow upon the world. A wizard must pursue the shadow he has created across the archipelago of Earthsea before it can find and devour him.',
    audience: "Children's",
    subgenres: ['High Fantasy', 'Coming of Age Fantasy'],
    tropes: ['Magic Academy', 'Coming of Age', 'Chosen One', 'Reluctant Hero'],
    magic_system: 'Hard Magic',
    tone: ['Philosophical', 'Atmospheric', 'Character-driven'],
    pacing: 'Mixed',
    heat_level: 'Clean',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: 'Dune',
    slug: 'dune',
    authors: ['Frank Herbert'],
    isbn: '9780441013593',
    cover_url: cover('9780441013593'),
    publication_year: 1965,
    page_count: 412,
    avg_rating: 4.25,
    synopsis:
      'Set on the desert planet Arrakis, Dune is the story of Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the spice melange—a drug capable of extending life and enhancing consciousness. When House Atreides is betrayed, the destruction of Paul\'s family will set the boy on a journey toward a destiny greater than he could ever have imagined.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'Science Fantasy'],
    tropes: ['Chosen One', 'Political Intrigue', 'Prophecy', 'Revenge Story', 'Coming of Age'],
    magic_system: 'Soft Magic',
    tone: ['Philosophical', 'Dark & Serious', 'Atmospheric'],
    pacing: 'Slow-burn',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Fourth Wing',
    slug: 'fourth-wing',
    authors: ['Rebecca Yarros'],
    isbn: '9781649374042',
    cover_url: cover('9781649374042'),
    publication_year: 2023,
    page_count: 517,
    avg_rating: 4.20,
    synopsis:
      'Twenty-three-year-old Violet Sorrengail was supposed to enter the Scribes Quadrant, but her mother—the commanding general—has other ideas. Attend the war college. Become a dragon rider. But the Riders Quadrant is the most dangerous place for someone who doesn\'t look like she can hack it—unless she finds the most powerful and ruthless rider there is to protect her.',
    audience: 'Adult',
    subgenres: ['Romantic Fantasy', 'Epic Fantasy'],
    tropes: ['Enemies to Lovers', 'Dragon Rider', 'Magic Academy', 'Forbidden Romance'],
    magic_system: 'Hard Magic',
    tone: ['Action-packed', 'Dark & Serious'],
    pacing: 'Fast-paced',
    heat_level: 'Spicy',
    diversity_rep: ['Disability Rep'],
  },
  {
    title: 'Iron Flame',
    slug: 'iron-flame',
    authors: ['Rebecca Yarros'],
    isbn: '9781649374172',
    cover_url: cover('9781649374172'),
    publication_year: 2023,
    page_count: 623,
    avg_rating: 4.10,
    synopsis:
      'The empyrean is at war. Violet Sorrengail faces a new year at Basgiath War College where the rules have changed—allies have become enemies and Violet finds herself in the middle of a conflict that could destroy everything. Some battles can only be won by the rider willing to risk everything.',
    audience: 'Adult',
    subgenres: ['Romantic Fantasy', 'Epic Fantasy'],
    tropes: ['Enemies to Lovers', 'Dragon Rider', 'Political Intrigue', 'Forbidden Romance'],
    magic_system: 'Hard Magic',
    tone: ['Action-packed', 'Dark & Serious'],
    pacing: 'Fast-paced',
    heat_level: 'Spicy',
    diversity_rep: ['Disability Rep'],
  },
  {
    title: 'The Cruel Prince',
    slug: 'the-cruel-prince',
    authors: ['Holly Black'],
    isbn: '9780316310314',
    cover_url: cover('9780316310314'),
    publication_year: 2018,
    page_count: 370,
    avg_rating: 4.05,
    synopsis:
      'Jude was seven when her parents were murdered and she and her two sisters were stolen away to live in the treacherous High Court of Faerie. Ten years later, she still feels like an outsider, uncertain of her place in the brutal shifting political landscape of a world filled with glamour and lies.',
    audience: 'Young Adult (YA)',
    subgenres: ['Romantic Fantasy', 'High Fantasy'],
    tropes: ['Fae Court Drama', 'Enemies to Lovers', 'Political Intrigue', 'Forbidden Romance'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Action-packed'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Children of Blood and Bone',
    slug: 'children-of-blood-and-bone',
    authors: ['Tomi Adeyemi'],
    isbn: '9781250170972',
    cover_url: cover('9781250170972'),
    publication_year: 2018,
    page_count: 531,
    avg_rating: 3.90,
    synopsis:
      'Zélie Adeyemi remembers when the soil of Orïsha hummed with magic. Then, in one dark night, everything changed—maji were killed and magic disappeared. Now Zélie has one chance to bring back magic and strike against the monarchy that took everything from her.',
    audience: 'Young Adult (YA)',
    subgenres: ['Epic Fantasy', 'High Fantasy'],
    tropes: ['Chosen One', 'Quest', 'Coming of Age', 'Political Intrigue'],
    magic_system: 'Hard Magic',
    tone: ['Action-packed', 'Dark & Serious', 'Hopeful'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: 'Throne of Glass',
    slug: 'throne-of-glass',
    authors: ['Sarah J. Maas'],
    isbn: '9781599906959',
    cover_url: cover('9781599906959'),
    publication_year: 2012,
    page_count: 404,
    avg_rating: 3.97,
    synopsis:
      'In a land without magic, where the king rules with an iron hand, an assassin is summoned to the castle to compete in a deadly tournament. If she defeats twenty-three killers, thieves, and warriors, she is released from prison and serves as the king\'s champion. Her name is Celaena Sardothien.',
    audience: 'Young Adult (YA)',
    subgenres: ['High Fantasy', 'Romantic Fantasy'],
    tropes: ['Tournament Arc', 'Enemies to Lovers', 'Coming of Age', 'Political Intrigue', 'Secret Identity'],
    magic_system: 'Soft Magic',
    tone: ['Action-packed', 'Dark & Serious'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Shadow and Bone',
    slug: 'shadow-and-bone',
    authors: ['Leigh Bardugo'],
    isbn: '9780805094596',
    cover_url: cover('9780805094596'),
    publication_year: 2012,
    page_count: 358,
    avg_rating: 4.00,
    synopsis:
      'Orphan soldier Alina Starkov has never been good at anything. But when her regiment is attacked on the Shadow Fold and her best friend is brutally injured, Alina reveals a dormant power that saves his life—a power that could be the key to setting her war-ravaged country free.',
    audience: 'Young Adult (YA)',
    subgenres: ['High Fantasy', 'Dark Fantasy'],
    tropes: ['Chosen One', 'Enemies to Lovers', 'Forbidden Romance', 'Political Intrigue'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Action-packed'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'The Song of Achilles',
    slug: 'the-song-of-achilles',
    authors: ['Madeline Miller'],
    isbn: '9780062060624',
    cover_url: cover('9780062060624'),
    publication_year: 2012,
    page_count: 352,
    avg_rating: 4.34,
    synopsis:
      'Greece in the age of heroes. Patroclus, an awkward young prince, has been exiled to the court of King Peleus and his perfect son Achilles. Despite their differences, Achilles befriends the shamed prince, and as they grow into young men their bond blossoms into something deeper—despite the displeasure of Achilles\' mother Thetis, a cruel sea goddess, and a war on the horizon.',
    audience: 'Adult',
    subgenres: ['Mythic Fantasy', 'Historical Fantasy'],
    tropes: ['Forbidden Romance', 'Slow Burn'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Character-driven', 'Philosophical'],
    pacing: 'Slow-burn',
    heat_level: 'Steamy',
    diversity_rep: ['LGBTQ+ Protagonist'],
  },
  {
    title: 'The Bear and the Nightingale',
    slug: 'the-bear-and-the-nightingale',
    authors: ['Katherine Arden'],
    isbn: '9781101885932',
    cover_url: cover('9781101885932'),
    publication_year: 2017,
    page_count: 323,
    avg_rating: 4.10,
    synopsis:
      'At the edge of the Russian wilderness, winter lasts most of the year. Vasilisa loves the long winters and the bright cold of the forest, where she is at home among the spirits of the wood. When a priest arrives preaching that the old ways are evil, her family must choose between new faith and old magic—with deadly consequences.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'Mythic Fantasy'],
    tropes: ['Coming of Age', 'Reluctant Hero', 'Slow Burn'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Dark & Serious', 'Whimsical'],
    pacing: 'Slow-burn',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'Babel',
    slug: 'babel',
    authors: ['R.F. Kuang'],
    isbn: '9780063021426',
    cover_url: cover('9780063021426'),
    publication_year: 2022,
    page_count: 545,
    avg_rating: 4.25,
    synopsis:
      '1828. Robin Swift, orphaned in Canton, is brought to London by a mysterious professor to train for Oxford\'s Royal Institute of Translation—known as Babel. Babel is the world\'s center of silver-working: the art of manifesting the meaning lost in translation through enchanted silver bars. But silver-working also powers the British Empire, and Robin must choose where his loyalties lie.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'Dark Fantasy'],
    tropes: ['Magic Academy', 'Coming of Age', 'Political Intrigue', 'Revenge Story', 'Found Family'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Philosophical'],
    pacing: 'Mixed',
    heat_level: 'Clean',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: "Assassin's Apprentice",
    slug: 'assassins-apprentice',
    authors: ['Robin Hobb'],
    isbn: '9780553573398',
    cover_url: cover('9780553573398'),
    publication_year: 1995,
    page_count: 356,
    avg_rating: 4.15,
    synopsis:
      'Young Fitz is the bastard son of the noble Prince Chivalry, raised in the shadow of the royal court by his father\'s stableman. When Fitz is finally adopted into the royal household, he must give up his only friend and begin his training as a royal assassin—with access to the mysterious magic known as the Skill.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'High Fantasy'],
    tropes: ['Coming of Age', 'Political Intrigue', 'Betrayal'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Character-driven', 'Philosophical'],
    pacing: 'Slow-burn',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'The Fifth Season',
    slug: 'the-fifth-season',
    authors: ['N.K. Jemisin'],
    isbn: '9780316229296',
    cover_url: cover('9780316229296'),
    publication_year: 2015,
    page_count: 468,
    avg_rating: 4.30,
    synopsis:
      'This is the way the world ends. Again. Three women are torn apart by catastrophe on a continent long familiar with apocalypse, where the power of the earth can be wielded for destruction or salvation. Their stories interweave into a tale of survival, power, and the lengths a mother will go for her child.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'Dark Fantasy', 'Science Fantasy'],
    tropes: ['Chosen One', 'Political Intrigue', 'Survival Journey', 'Betrayal'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Philosophical'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: ['POC Protagonist', 'LGBTQ+ Side Characters'],
  },
  {
    title: 'Uprooted',
    slug: 'uprooted',
    authors: ['Naomi Novik'],
    isbn: '9780804179034',
    cover_url: cover('9780804179034'),
    publication_year: 2015,
    page_count: 438,
    avg_rating: 4.05,
    synopsis:
      'Agnieszka loves her valley home. But the corrupted Wood stands on the border, full of malevolent power, and her people rely on the cold wizard known only as the Dragon to keep its influence at bay. Every ten years he takes a girl from the valley as his apprentice—and this year, he chooses Agnieszka.',
    audience: 'Adult',
    subgenres: ['High Fantasy', 'Mythic Fantasy'],
    tropes: ['Enemies to Lovers', 'Slow Burn', 'Curse Breaking', 'Coming of Age'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Character-driven', 'Dark & Serious'],
    pacing: 'Mixed',
    heat_level: 'Steamy',
    diversity_rep: [],
  },
  {
    title: 'A Darker Shade of Magic',
    slug: 'a-darker-shade-of-magic',
    authors: ['V.E. Schwab'],
    isbn: '9780765376459',
    cover_url: cover('9780765376459'),
    publication_year: 2015,
    page_count: 400,
    avg_rating: 4.20,
    synopsis:
      'Kell is one of the last Antari—magicians with a rare ability to travel between parallel Londons: Red, Grey, White, and once, Black. He serves as an ambassador between worlds, but his black market activities land him with a magical artefact that could be the end of all the Londons.',
    audience: 'Adult',
    subgenres: ['High Fantasy', 'Portal Fantasy'],
    tropes: ['Heist', 'Political Intrigue', 'Found Family', 'Secret Identity'],
    magic_system: 'Hard Magic',
    tone: ['Action-packed', 'Dark & Serious'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'The Invisible Life of Addie LaRue',
    slug: 'the-invisible-life-of-addie-larue',
    authors: ['V.E. Schwab'],
    isbn: '9780765387561',
    cover_url: cover('9780765387561'),
    publication_year: 2020,
    page_count: 444,
    avg_rating: 4.10,
    synopsis:
      'France, 1714: in a moment of desperation, a young woman makes a Faustian bargain to live forever—and is cursed to be forgotten by everyone she meets. Thus begins the extraordinary life of Addie LaRue, and a 300-year story of a deal struck with a god of darkness.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'Urban Fantasy', 'Contemporary Fantasy'],
    tropes: ['Slow Burn', 'Forbidden Romance', 'Curse Breaking'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Character-driven', 'Philosophical'],
    pacing: 'Slow-burn',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Guards! Guards!',
    slug: 'guards-guards',
    authors: ['Terry Pratchett'],
    isbn: '9780062225757',
    cover_url: cover('9780062225757'),
    publication_year: 1989,
    page_count: 288,
    avg_rating: 4.30,
    synopsis:
      'A superb specimen of draco nobilis has appeared in Discworld\'s greatest city of Ankh-Morpork. Who summoned it? Why? And what happens when it\'s taken over by a very small, very angry secret brotherhood? The Night Watch—led by the world-weary Captain Vimes—must find out.',
    audience: 'Adult',
    subgenres: ['Humorous Fantasy', 'Epic Fantasy'],
    tropes: ['Quest', 'Dragons', 'Found Family', 'Political Intrigue'],
    magic_system: 'Soft Magic',
    tone: ['Humorous', 'Whimsical', 'Satirical'],
    pacing: 'Fast-paced',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'Spinning Silver',
    slug: 'spinning-silver',
    authors: ['Naomi Novik'],
    isbn: '9781524799526',
    cover_url: cover('9781524799526'),
    publication_year: 2018,
    page_count: 480,
    avg_rating: 4.10,
    synopsis:
      'Miryem is the daughter of moneylenders, but her father\'s inability to collect debts has left the family starving. When she takes matters into her own hands and gains a reputation for turning silver into gold, a magical debt-collector shows up—and she is forced to make good on her boast or be taken into his frozen domain forever.',
    audience: 'Adult',
    subgenres: ['Mythic Fantasy', 'Historical Fantasy'],
    tropes: ['Enemies to Lovers', 'Slow Burn', 'Curse Breaking', 'Found Family'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Dark & Serious', 'Character-driven'],
    pacing: 'Slow-burn',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    slug: 'the-hitchhikers-guide-to-the-galaxy',
    authors: ['Douglas Adams'],
    isbn: '9780345391803',
    cover_url: cover('9780345391803'),
    publication_year: 1979,
    page_count: 193,
    avg_rating: 4.22,
    synopsis:
      'Seconds before the Earth is demolished to make way for a hyperspatial express route, Arthur Dent is plucked off the planet by his friend Ford Prefect. Together they begin a journey through space aided by quotes from The Hitchhiker\'s Guide ("A towel is about the most massively useful thing an interstellar hitchhiker can have") and a galaxy-full of fellow travellers.',
    audience: 'Adult',
    subgenres: ['Science Fantasy', 'Humorous Fantasy'],
    tropes: ['Quest', 'Found Family'],
    magic_system: 'No Magic',
    tone: ['Humorous', 'Whimsical', 'Satirical'],
    pacing: 'Fast-paced',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: "Ender's Game",
    slug: 'enders-game',
    authors: ['Orson Scott Card'],
    isbn: '9780812550702',
    cover_url: cover('9780812550702'),
    publication_year: 1985,
    page_count: 226,
    avg_rating: 4.30,
    synopsis:
      'Andrew "Ender" Wiggin thinks he is playing computer simulated war games; he is in fact engaged in something far more desperate. The result of genetic experimentation, Ender may be the military genius Earth\'s desperate leaders need. The war with the alien Buggers has been raging for a hundred years, and the quest for the perfect general has been underway almost as long.',
    audience: 'Young Adult (YA)',
    subgenres: ['Science Fantasy', 'Military Fantasy'],
    tropes: ['Chosen One', 'Coming of Age', 'Tournament Arc', 'Political Intrigue'],
    magic_system: 'No Magic',
    tone: ['Dark & Serious', 'Action-packed', 'Philosophical'],
    pacing: 'Fast-paced',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'Prince of Thorns',
    slug: 'prince-of-thorns',
    authors: ['Mark Lawrence'],
    isbn: '9780441020683',
    cover_url: cover('9780441020683'),
    publication_year: 2011,
    page_count: 338,
    avg_rating: 3.85,
    synopsis:
      'Before the thorns taught me their sharp lessons and bled weakness from me I had but one brother, and I loved him well. Prince Jorg of Ancrath leads a band of bloodthirsty outlaws through a fractured empire in pursuit of vengeance—and a throne.',
    audience: 'Adult',
    subgenres: ['Grimdark', 'Dark Fantasy', 'Epic Fantasy'],
    tropes: ['Anti-Hero', 'Revenge Story', 'Political Intrigue', 'Betrayal'],
    magic_system: 'Soft Magic',
    tone: ['Grimdark', 'Dark & Serious'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'The Hundred Thousand Kingdoms',
    slug: 'the-hundred-thousand-kingdoms',
    authors: ['N.K. Jemisin'],
    isbn: '9780316043960',
    cover_url: cover('9780316043960'),
    publication_year: 2010,
    page_count: 427,
    avg_rating: 3.90,
    synopsis:
      'Yeine Darr is an outcast from the barbarian north. When her mother dies under mysterious circumstances, she is summoned to the majestic city of Sky and named an heiress to the king. But the throne is not easily won, and Yeine is thrust into a vicious power struggle with cousins she never knew—and gods who walk among mortals.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'Mythic Fantasy'],
    tropes: ['Political Intrigue', 'Forbidden Romance', 'Chosen One'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Atmospheric', 'Character-driven'],
    pacing: 'Mixed',
    heat_level: 'Steamy',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: 'Jonathan Strange & Mr Norrell',
    slug: 'jonathan-strange-and-mr-norrell',
    authors: ['Susanna Clarke'],
    isbn: '9781582344164',
    cover_url: cover('9781582344164'),
    publication_year: 2004,
    page_count: 846,
    avg_rating: 3.95,
    synopsis:
      'In the early nineteenth century, two magicians emerge to change England\'s history. The reclusive Mr Norrell has been preparing for years to restore English magic. The young Jonathan Strange has a wilder, more unpredictable talent. Together they help England fight Napoleon—but soon they are at war with each other.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'High Fantasy'],
    tropes: ['Magic Academy', 'Political Intrigue', 'Mentor Figure'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Philosophical', 'Humorous'],
    pacing: 'Slow-burn',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'Gardens of the Moon',
    slug: 'gardens-of-the-moon',
    authors: ['Steven Erikson'],
    isbn: '9780765348784',
    cover_url: cover('9780765348784'),
    publication_year: 1999,
    page_count: 666,
    avg_rating: 3.80,
    synopsis:
      'The Malazan Empire simmers with discontent, betrayal and murder. The armies of the Empress have shattered long-established kingdoms and taken over the world. Now the gods themselves are taking sides. The Bridgeburners—a company of battered soldiers—find themselves pawns in a game between mortals and immortals, caught in a siege of the fabled city of Darujhistan.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'High Fantasy', 'Grimdark'],
    tropes: ['Political Intrigue', 'Found Family', 'Quest', 'Betrayal'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Grimdark', 'Action-packed'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  // --- Batch 3 ---
  {
    title: 'The Eye of the World',
    slug: 'the-eye-of-the-world',
    authors: ['Robert Jordan'],
    isbn: '9780812511819',
    cover_url: cover('9780812511819'),
    publication_year: 1990,
    page_count: 782,
    avg_rating: 4.19,
    synopsis:
      'The Wheel of Time turns and Ages come and go, leaving memories that become legend. When the darkness stirs again, five young villagers from the Two Rivers are plucked from their ordinary lives and thrust into a world where they are hunted by the Dark One\'s forces. Among them may be the Dragon Reborn—the one destined to either save the world or break it.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'High Fantasy'],
    tropes: ['Chosen One', 'Quest', 'Dark Lord', 'Coming of Age', 'Found Family', 'Prophecy'],
    magic_system: 'Hard Magic',
    tone: ['Atmospheric', 'Action-packed', 'Hopeful'],
    pacing: 'Mixed',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'Words of Radiance',
    slug: 'words-of-radiance',
    authors: ['Brandon Sanderson'],
    isbn: '9780765326362',
    cover_url: cover('9780765326362'),
    publication_year: 2014,
    page_count: 1087,
    avg_rating: 4.77,
    synopsis:
      'Return to the world of the Stormlight Archive as the Alethi armies have finally breached the tower city of Urithiru. Shallan Davar travels to the Shattered Plains to find proof of her missing betrothed, and Kaladin continues his transformation from slave to soldier to something far greater.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'High Fantasy'],
    tropes: ['Chosen One', 'Political Intrigue', 'Quest', 'Coming of Age', 'Betrayal'],
    magic_system: 'Hard Magic',
    tone: ['Philosophical', 'Dark & Serious', 'Action-packed'],
    pacing: 'Slow-burn',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'Red Rising',
    slug: 'red-rising',
    authors: ['Pierce Brown'],
    isbn: '9780345539786',
    cover_url: cover('9780345539786'),
    publication_year: 2014,
    page_count: 382,
    avg_rating: 4.25,
    synopsis:
      'Darrow is a Red, a member of the lowest caste in a future society built on Mars. Believing he is mining the planet to make it habitable for humanity, he discovers a devastating truth—Mars has been terraformed for centuries. His people are slaves. Darrow must infiltrate the Gold ruling class and destroy it from within.',
    audience: 'Adult',
    subgenres: ['Science Fantasy', 'Dystopian Fantasy'],
    tropes: ['Chosen One', 'Tournament Arc', 'Political Intrigue', 'Coming of Age', 'Secret Identity', 'Revenge Story'],
    magic_system: 'No Magic',
    tone: ['Dark & Serious', 'Action-packed', 'Hopeful'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'The Goblin Emperor',
    slug: 'the-goblin-emperor',
    authors: ['Katherine Addison'],
    isbn: '9780765365682',
    cover_url: cover('9780765365682'),
    publication_year: 2014,
    page_count: 447,
    avg_rating: 4.10,
    synopsis:
      'The youngest, half-goblin son of the Emperor has lived his entire life in exile, shamed for his parentage. When the emperor and his other sons are killed in an airship crash, Maia is suddenly the Emperor of the Elflands—and must navigate a court he knows nothing about, with no allies and a dozen enemies waiting for him to fail.',
    audience: 'Adult',
    subgenres: ['High Fantasy', 'Cozy Fantasy'],
    tropes: ['Reluctant Hero', 'Political Intrigue', 'Coming of Age', 'Found Family'],
    magic_system: 'Soft Magic',
    tone: ['Whimsical', 'Character-driven', 'Hopeful'],
    pacing: 'Mixed',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'Sabriel',
    slug: 'sabriel',
    authors: ['Garth Nix'],
    isbn: '9780064471831',
    cover_url: cover('9780064471831'),
    publication_year: 1995,
    page_count: 292,
    avg_rating: 4.12,
    synopsis:
      'Sent to a boarding school in Ancelstierre as a young child, Sabriel has had little reason to return to the Old Kingdom, where the dead do not always stay dead. But now her father—the Abhorsen—has gone missing, and Sabriel must cross the border into that magical country to find him and rescue him from Death itself.',
    audience: 'Young Adult (YA)',
    subgenres: ['High Fantasy', 'Dark Fantasy'],
    tropes: ['Chosen One', 'Quest', 'Coming of Age'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Atmospheric', 'Action-packed'],
    pacing: 'Fast-paced',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'Neverwhere',
    slug: 'neverwhere',
    authors: ['Neil Gaiman'],
    isbn: '9780060557812',
    cover_url: cover('9780060557812'),
    publication_year: 1996,
    page_count: 370,
    avg_rating: 4.17,
    synopsis:
      'Richard Mayhew is a young London businessman with a perfectly normal life—until he stops to help a girl bleeding on the pavement. His act of charity drops him into a world he never knew existed, a city of monsters and saints, murderers and angels, that lives in the hidden gaps and secret places of London Below.',
    audience: 'Adult',
    subgenres: ['Urban Fantasy', 'Contemporary Fantasy'],
    tropes: ['Portal Fantasy', 'Reluctant Hero', 'Found Family', 'Quest'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Whimsical', 'Atmospheric'],
    pacing: 'Fast-paced',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'The Princess Bride',
    slug: 'the-princess-bride',
    authors: ['William Goldman'],
    isbn: '9780156035217',
    cover_url: cover('9780156035217'),
    publication_year: 1973,
    page_count: 283,
    avg_rating: 4.22,
    synopsis:
      'Beautiful Buttercup is kidnapped by a power-hungry prince, and her true love Westley—now the notorious Dread Pirate Roberts—must rescue her with the help of a gentle giant, a vengeful swordsman, and a brilliant criminal mastermind. A swashbuckling fairy tale of love, treachery, and revenge.',
    audience: 'Adult',
    subgenres: ['Humorous Fantasy', 'High Fantasy'],
    tropes: ['Quest', 'Forbidden Romance', 'Reluctant Hero', 'Heist'],
    magic_system: 'No Magic',
    tone: ['Humorous', 'Whimsical', 'Light-hearted'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'The Starless Sea',
    slug: 'the-starless-sea',
    authors: ['Erin Morgenstern'],
    isbn: '9780385541213',
    cover_url: cover('9780385541213'),
    publication_year: 2019,
    page_count: 498,
    avg_rating: 3.90,
    synopsis:
      'Zachary Ezra Rawlins stumbles across a book in his university library that contains a story from his own childhood. He follows a series of clues leading him to a subterranean world beneath a hotel—a place of pirates, painters, lovers, and assassins. A timeless love story set in an underground sea of story.',
    audience: 'Adult',
    subgenres: ['Contemporary Fantasy', 'Romantic Fantasy'],
    tropes: ['Portal Fantasy', 'Found Family', 'Forbidden Romance', 'Slow Burn'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Whimsical', 'Philosophical'],
    pacing: 'Slow-burn',
    heat_level: 'Fade to Black',
    diversity_rep: ['LGBTQ+ Protagonist'],
  },
  {
    title: 'Strange the Dreamer',
    slug: 'strange-the-dreamer',
    authors: ['Laini Taylor'],
    isbn: '9780316341677',
    cover_url: cover('9780316341677'),
    publication_year: 2017,
    page_count: 532,
    avg_rating: 4.13,
    synopsis:
      'The dream chooses the dreamer, not the other way around—and Lazlo Strange, war orphan and junior librarian, has always felt he was meant for another world. When a mythic city appears out of nowhere and a band of legendary warriors arrives to recruit people for a rescue mission, Lazlo must decide how far to follow his dreams.',
    audience: 'Young Adult (YA)',
    subgenres: ['High Fantasy', 'Romantic Fantasy'],
    tropes: ['Forbidden Romance', 'Chosen One', 'Coming of Age', 'Quest'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Whimsical', 'Character-driven'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'From Blood and Ash',
    slug: 'from-blood-and-ash',
    authors: ['Jennifer L. Armentrout'],
    isbn: '9781952457760',
    cover_url: cover('9781952457760'),
    publication_year: 2020,
    page_count: 622,
    avg_rating: 4.05,
    synopsis:
      'Poppy has never been like other girls. Chosen from birth to usher in a new era, she\'s been forbidden from being touched, has never known friendship or freedom, and is guarded by a golden boy who makes her want things she can\'t have. A story of fate, sacrifice, and discovering who you really are.',
    audience: 'Adult',
    subgenres: ['Romantic Fantasy', 'High Fantasy'],
    tropes: ['Enemies to Lovers', 'Forbidden Romance', 'Chosen One', 'Secret Identity'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Action-packed'],
    pacing: 'Fast-paced',
    heat_level: 'Spicy',
    diversity_rep: [],
  },
  {
    title: 'Eragon',
    slug: 'eragon',
    authors: ['Christopher Paolini'],
    isbn: '9780375826696',
    cover_url: cover('9780375826696'),
    publication_year: 2003,
    page_count: 503,
    avg_rating: 3.82,
    synopsis:
      'When fifteen-year-old Eragon finds a polished blue stone in the mountains, he has no idea it will change his life forever. The stone hatches into a dragon, and Eragon soon discovers that he is the first Dragon Rider to be born in a generation—a fact that will make him either the savior or the ruin of the Empire.',
    audience: 'Young Adult (YA)',
    subgenres: ['High Fantasy', 'Epic Fantasy'],
    tropes: ['Chosen One', 'Quest', 'Dragon Rider', 'Coming of Age', 'Mentor Figure'],
    magic_system: 'Hard Magic',
    tone: ['Action-packed', 'Atmospheric', 'Hopeful'],
    pacing: 'Mixed',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'City of Bones',
    slug: 'city-of-bones',
    authors: ['Cassandra Clare'],
    isbn: '9781416955078',
    cover_url: cover('9781416955078'),
    publication_year: 2007,
    page_count: 485,
    avg_rating: 3.88,
    synopsis:
      'When fifteen-year-old Clary Fray heads out to a New York City club with her best friend Simon, she witnesses a murder committed by three teens who seem to have appeared out of thin air. Drawn into the dangerous world of the Shadowhunters—warriors dedicated to ridding the earth of demons—she discovers she has a heritage that will change everything.',
    audience: 'Young Adult (YA)',
    subgenres: ['Urban Fantasy', 'Dark Fantasy'],
    tropes: ['Chosen One', 'Coming of Age', 'Forbidden Romance', 'Secret Identity', 'Found Family'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Action-packed'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: ['LGBTQ+ Side Characters'],
  },
  {
    title: 'The Last Wish',
    slug: 'the-last-wish',
    authors: ['Andrzej Sapkowski'],
    isbn: '9780316029186',
    cover_url: cover('9780316029186'),
    publication_year: 1993,
    page_count: 288,
    avg_rating: 4.21,
    synopsis:
      'Geralt of Rivia is a witcher. A cunning sorcerer, a ruthless assassin and a cold-blooded killer—yet caring and emotional at the same time. Contracted by village elders and nobles alike to hunt down the monsters that terrorise their lands, Geralt must use his mutant skills to survive in a world where being a monster is not always as straightforward as it seems.',
    audience: 'Adult',
    subgenres: ['Dark Fantasy', 'Low Fantasy', 'Grimdark'],
    tropes: ['Anti-Hero', 'Quest', 'Political Intrigue', 'Morally Grey Hero'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Humorous', 'Philosophical'],
    pacing: 'Mixed',
    heat_level: 'Steamy',
    diversity_rep: [],
  },
  {
    title: 'The Graveyard Book',
    slug: 'the-graveyard-book',
    authors: ['Neil Gaiman'],
    isbn: '9780060530921',
    cover_url: cover('9780060530921'),
    publication_year: 2008,
    page_count: 312,
    avg_rating: 4.08,
    synopsis:
      'After his family is murdered, a toddler wanders into a nearby graveyard. The ghosts who live there—led by the kindly Mr. and Mrs. Owens—agree to raise the boy, Nobody "Bod" Owens. Bod grows up learning the ways of the dead while the man who killed his family still hunts for him.',
    audience: "Children's",
    subgenres: ['Urban Fantasy', 'Contemporary Fantasy', 'Dark Fantasy'],
    tropes: ['Coming of Age', 'Found Family'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Whimsical', 'Atmospheric'],
    pacing: 'Mixed',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'Stardust',
    slug: 'stardust',
    authors: ['Neil Gaiman'],
    isbn: '9780061689246',
    cover_url: cover('9780061689246'),
    publication_year: 1999,
    page_count: 248,
    avg_rating: 4.08,
    synopsis:
      'Young Tristran Thorn promises his heart\'s desire—the beautiful Victoria—that he will retrieve a fallen star from beyond the Wall that separates their village from the enchanted kingdom of Faerie. What he finds is not a lump of rock but a young woman named Yvaine, who is not at all pleased to be captured.',
    audience: 'Adult',
    subgenres: ['High Fantasy', 'Romantic Fantasy', 'Fae Fantasy'],
    tropes: ['Quest', 'Enemies to Lovers', 'Fae Court Drama'],
    magic_system: 'Soft Magic',
    tone: ['Whimsical', 'Light-hearted', 'Atmospheric'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Graceling',
    slug: 'graceling',
    authors: ['Kristin Cashore'],
    isbn: '9780152063962',
    cover_url: cover('9780152063962'),
    publication_year: 2008,
    page_count: 471,
    avg_rating: 3.98,
    synopsis:
      'Katsa lives in the Seven Kingdoms, where people born with extreme skill are called Gracelings—and marked with mismatched eyes to warn others of their dangerous gift. Katsa\'s grace is killing. She has never understood herself to be anything more than the king\'s weapon—until she meets a mysterious Graceling fighter named Po.',
    audience: 'Young Adult (YA)',
    subgenres: ['High Fantasy', 'Romantic Fantasy'],
    tropes: ['Enemies to Lovers', 'Coming of Age', 'Reluctant Hero', 'Political Intrigue'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Action-packed', 'Character-driven'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Best Served Cold',
    slug: 'best-served-cold',
    authors: ['Joe Abercrombie'],
    isbn: '9781591027577',
    cover_url: cover('9781591027577'),
    publication_year: 2009,
    page_count: 531,
    avg_rating: 4.20,
    synopsis:
      'Monza Murcatto, the Snake of Talins, is the most feared mercenary general in the Styrian wars. When she is betrayed by the Grand Duke she serves and left for dead, she begins a ruthless campaign of revenge—one where the line between justice and monstrosity is dangerously thin.',
    audience: 'Adult',
    subgenres: ['Grimdark', 'Epic Fantasy'],
    tropes: ['Revenge Story', 'Anti-Hero', 'Heist', 'Betrayal', 'Political Intrigue'],
    magic_system: 'Soft Magic',
    tone: ['Grimdark', 'Dark & Serious', 'Humorous'],
    pacing: 'Fast-paced',
    heat_level: 'Steamy',
    diversity_rep: [],
  },
  {
    title: 'A Memory Called Empire',
    slug: 'a-memory-called-empire',
    authors: ['Arkady Martine'],
    isbn: '9781250186430',
    cover_url: cover('9781250186430'),
    publication_year: 2019,
    page_count: 462,
    avg_rating: 4.07,
    synopsis:
      'Ambassador Mahit Dzmare arrives in the Teixcalaanli Empire to find her predecessor dead—and no one willing to admit it. She is sent to discover what really happened, while navigating a glittering, treacherous court where even language is a weapon and assimilation is pressure. A space opera about power, identity, and belonging.',
    audience: 'Adult',
    subgenres: ['Science Fantasy', 'Political Fantasy'],
    tropes: ['Political Intrigue', 'Secret Identity', 'Slow Burn', 'Forbidden Romance'],
    magic_system: 'No Magic',
    tone: ['Atmospheric', 'Philosophical', 'Dark & Serious'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: ['LGBTQ+ Protagonist', 'POC Protagonist'],
  },
  {
    title: 'The Bone Shard Daughter',
    slug: 'the-bone-shard-daughter',
    authors: ['Andrea Stewart'],
    isbn: '9780316541435',
    cover_url: cover('9780316541435'),
    publication_year: 2020,
    page_count: 435,
    avg_rating: 3.98,
    synopsis:
      'The emperor rules with a magic built of stolen children\'s memories. His palace is filled with constructs—part animal, part human—powered by bone shards from living subjects who weaken and die as the magic drains them. His daughter Lin must find the secrets of the bone shard magic before a rebellion tears their empire apart.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'Dark Fantasy'],
    tropes: ['Political Intrigue', 'Chosen One', 'Secret Identity', 'Coming of Age'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Atmospheric'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: 'The Atlas Six',
    slug: 'the-atlas-six',
    authors: ['Olivie Blake'],
    isbn: '9781250895370',
    cover_url: cover('9781250895370'),
    publication_year: 2020,
    page_count: 373,
    avg_rating: 3.80,
    synopsis:
      'The Alexandrian Society is a secret organization of the world\'s most dangerous magical scholars. Every decade, six magicians are invited to compete for initiation—and one will be eliminated. When Libby Rhodes and Nico de Varona find themselves recruited together, they must cooperate or die while navigating a house full of the most brilliant and treacherous minds on earth.',
    audience: 'Adult',
    subgenres: ['Dark Fantasy', 'High Fantasy'],
    tropes: ['Magic Academy', 'Tournament Arc', 'Enemies to Lovers', 'Political Intrigue', 'Found Family'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Philosophical'],
    pacing: 'Slow-burn',
    heat_level: 'Fade to Black',
    diversity_rep: ['LGBTQ+ Side Characters', 'POC Side Characters'],
  },
  {
    title: 'The Magicians',
    slug: 'the-magicians',
    authors: ['Lev Grossman'],
    isbn: '9780670020553',
    cover_url: cover('9780670020553'),
    publication_year: 2009,
    page_count: 402,
    avg_rating: 3.59,
    synopsis:
      'Quentin Coldwater is clever but unhappy, obsessed with a series of fantasy novels about a magical land called Fillory. When he is unexpectedly admitted to Brakebills College for Magical Pedagogy, he discovers that the magic he read about as a child is real—but so is the darkness that comes with it.',
    audience: 'Adult',
    subgenres: ['Contemporary Fantasy', 'Dark Fantasy'],
    tropes: ['Magic Academy', 'Coming of Age', 'Chosen One', 'Portal Fantasy'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Philosophical'],
    pacing: 'Mixed',
    heat_level: 'Steamy',
    diversity_rep: [],
  },
  {
    title: 'Nevernight',
    slug: 'nevernight',
    authors: ['Jay Kristoff'],
    isbn: '9781250301055',
    cover_url: cover('9781250301055'),
    publication_year: 2016,
    page_count: 448,
    avg_rating: 4.10,
    synopsis:
      'Mia Corvere is barely sixteen years old when she is given a chance to train at a secret school for killers. She has spent years preparing for this, fueled by a thirst for revenge against the men who destroyed her family. But the Red Church is no place for the faint of heart—and the competition is deadly.',
    audience: 'Adult',
    subgenres: ['Dark Fantasy', 'High Fantasy'],
    tropes: ['Magic Academy', 'Revenge Story', 'Anti-Hero', 'Coming of Age', 'Forbidden Romance'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Action-packed', 'Humorous'],
    pacing: 'Fast-paced',
    heat_level: 'Spicy',
    diversity_rep: [],
  },
  {
    title: 'The Black Prism',
    slug: 'the-black-prism',
    authors: ['Brent Weeks'],
    isbn: '9780316246293',
    cover_url: cover('9780316246293'),
    publication_year: 2010,
    page_count: 641,
    avg_rating: 4.14,
    synopsis:
      'Guile is the Prism—the most powerful man in the world, who can split light into magical luxin to create anything he desires. But every Prism before him has died young. When Guile discovers he has a son, the boy might be the key to saving the world—or destroying it.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'High Fantasy'],
    tropes: ['Chosen One', 'Political Intrigue', 'Secret Identity', 'Coming of Age'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Action-packed'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Foundryside',
    slug: 'foundryside',
    authors: ['Robert Jackson Bennett'],
    isbn: '9781524760366',
    cover_url: cover('9781524760366'),
    publication_year: 2018,
    page_count: 502,
    avg_rating: 4.16,
    synopsis:
      'In the city of Tevanne, merchants use scrived objects—artifacts imbued with magical sigils—to dominate trade and maintain power. Sancia Grado is a thief with a unique ability to communicate with scrived objects. When she steals something that could shatter the foundations of the entire world, she finds herself in the middle of a conspiracy far bigger than any heist.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'Low Fantasy'],
    tropes: ['Heist', 'Political Intrigue', 'Coming of Age', 'Found Family'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Action-packed'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: 'A Long Way to a Small, Angry Planet',
    slug: 'a-long-way-to-a-small-angry-planet',
    authors: ['Becky Chambers'],
    isbn: '9781500453305',
    cover_url: cover('9781500453305'),
    publication_year: 2014,
    page_count: 402,
    avg_rating: 4.19,
    synopsis:
      'Rosemary Harper joins the diverse crew of the Wayfarer, a tunnelling ship that creates wormhole highways. When they are offered a chance to make a lucrative run to the galactic core, the crew must journey far beyond charted space and discover that the most important—and dangerous—parts of the universe are the people you find along the way.',
    audience: 'Adult',
    subgenres: ['Science Fantasy'],
    tropes: ['Found Family', 'Quest'],
    magic_system: 'No Magic',
    tone: ['Whimsical', 'Character-driven', 'Hopeful', 'Humorous'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: ['LGBTQ+ Side Characters', 'POC Side Characters'],
  },
  {
    title: 'The Rage of Dragons',
    slug: 'the-rage-of-dragons',
    authors: ['Evan Winter'],
    isbn: '9780316489768',
    cover_url: cover('9780316489768'),
    publication_year: 2019,
    page_count: 544,
    avg_rating: 4.10,
    synopsis:
      'The Omehi people have been at war for two hundred years. Every generation, a handful of women are chosen as Gifted—able to call down dragons during battle. Tau knows exactly what he wants: to fight in the war to avenge his father\'s death, no matter the cost to himself or those around him.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'Grimdark'],
    tropes: ['Chosen One', 'Revenge Story', 'Coming of Age', 'Tournament Arc', 'Dragon Rider'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Action-packed', 'Grimdark'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: 'Empire of Sand',
    slug: 'empire-of-sand',
    authors: ['Tasha Suri'],
    isbn: '9780316449953',
    cover_url: cover('9780316449953'),
    publication_year: 2018,
    page_count: 439,
    avg_rating: 3.93,
    synopsis:
      'In the Ambhan Empire, Mehr is the illegitimate daughter of an imperial governor and a woman of the nomadic Amrithi people. When the Empire discovers her heritage, she is forced to marry a mystic of the Emperor\'s order—and discovers that the power she carries in her blood could either bind or free her.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'Romantic Fantasy'],
    tropes: ['Forbidden Romance', 'Political Intrigue', 'Slow Burn'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Dark & Serious', 'Character-driven'],
    pacing: 'Mixed',
    heat_level: 'Steamy',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: 'The Jasmine Throne',
    slug: 'the-jasmine-throne',
    authors: ['Tasha Suri'],
    isbn: '9780316538541',
    cover_url: cover('9780316538541'),
    publication_year: 2021,
    page_count: 470,
    avg_rating: 4.10,
    synopsis:
      'Priya is a maidservant in the Parijati empire, hiding her nature as a temple child with magical abilities. Malini is an imperial princess imprisoned for defying her emperor brother. When they are thrown together, they must work to free themselves—and possibly shatter an empire—even as they fall for each other.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'Romantic Fantasy'],
    tropes: ['Enemies to Lovers', 'Political Intrigue', 'Forbidden Romance', 'Slow Burn'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Atmospheric', 'Character-driven'],
    pacing: 'Mixed',
    heat_level: 'Spicy',
    diversity_rep: ['POC Protagonist', 'LGBTQ+ Protagonist'],
  },
  {
    title: 'Storm Front',
    slug: 'storm-front',
    authors: ['Jim Butcher'],
    isbn: '9780451461872',
    cover_url: cover('9780451461872'),
    publication_year: 2000,
    page_count: 322,
    avg_rating: 3.92,
    synopsis:
      'Harry Dresden is Chicago\'s first (and only) professional wizard. He advertises in the Yellow Pages and works with the Chicago PD on cases involving the supernatural. When two victims are found with their hearts ripped out through magic, Harry must investigate—while keeping himself alive against the dark forces that want him dead.',
    audience: 'Adult',
    subgenres: ['Urban Fantasy', 'Contemporary Fantasy'],
    tropes: ['Anti-Hero', 'Quest', 'Political Intrigue'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Humorous', 'Action-packed'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Elantris',
    slug: 'elantris',
    authors: ['Brandon Sanderson'],
    isbn: '9780765350374',
    cover_url: cover('9780765350374'),
    publication_year: 2005,
    page_count: 492,
    avg_rating: 3.83,
    synopsis:
      'Elantris was the magical city, home to beings who could perform feats of wonder. Then the magic failed. The city fell into ruin, its inhabitants transformed into shambling wrecks. Now Prince Raoden, struck by the Shaod, is thrown into Elantris to die—but instead he must find a way to restore both the city and himself.',
    audience: 'Adult',
    subgenres: ['High Fantasy', 'Epic Fantasy'],
    tropes: ['Chosen One', 'Political Intrigue', 'Coming of Age', 'Curse Breaking'],
    magic_system: 'Hard Magic',
    tone: ['Hopeful', 'Dark & Serious', 'Character-driven'],
    pacing: 'Mixed',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  // --- Batch 4 ---
  {
    title: 'Tigana',
    slug: 'tigana',
    authors: ['Guy Gavriel Kay'],
    isbn: '9780451457769',
    cover_url: cover('9780451457769'),
    publication_year: 1990,
    page_count: 673,
    avg_rating: 4.27,
    synopsis:
      'The sorcerer Brandin has destroyed the kingdom of Tigana so completely that no one outside its borders can even speak its name—it has been erased from the world by magic. A small group of survivors plot to restore their land\'s identity, knowing they must overthrow a tyrant who has already proven he can unmake a nation.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'Epic Fantasy'],
    tropes: ['Political Intrigue', 'Betrayal', 'Revenge Story', 'Found Family'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Dark & Serious', 'Philosophical'],
    pacing: 'Slow-burn',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Caraval',
    slug: 'caraval',
    authors: ['Stephanie Garber'],
    isbn: '9781250095268',
    cover_url: cover('9781250095268'),
    publication_year: 2017,
    page_count: 407,
    avg_rating: 3.93,
    synopsis:
      'Scarlett has dreamed of attending Caraval—the legendary performance where the audience becomes a part of the show. When she finally receives an invitation, she discovers that this game is more dangerous than she imagined. In Caraval, even the smallest choices matter and every secret could be her last.',
    audience: 'Young Adult (YA)',
    subgenres: ['Romantic Fantasy', 'Contemporary Fantasy'],
    tropes: ['Quest', 'Forbidden Romance', 'Slow Burn', 'Enemies to Lovers'],
    magic_system: 'Soft Magic',
    tone: ['Whimsical', 'Atmospheric', 'Action-packed'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'The Ten Thousand Doors of January',
    slug: 'the-ten-thousand-doors-of-january',
    authors: ['Alix E. Harrow'],
    isbn: '9781250758637',
    cover_url: cover('9781250758637'),
    publication_year: 2019,
    page_count: 374,
    avg_rating: 3.96,
    synopsis:
      'In the early 1900s, a young woman named January discovers a mysterious book that tells her about Doors—passages to other worlds—and her own impossible place in a world of secrets and power. A lyrical story about the magic of words, the pull of other worlds, and the cost of belonging.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'Portal Fantasy'],
    tropes: ['Portal Fantasy', 'Coming of Age', 'Forbidden Romance'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Whimsical', 'Character-driven'],
    pacing: 'Slow-burn',
    heat_level: 'Fade to Black',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: 'The Dragon Republic',
    slug: 'the-dragon-republic',
    authors: ['R.F. Kuang'],
    isbn: '9780062662637',
    cover_url: cover('9780062662637'),
    publication_year: 2019,
    page_count: 658,
    avg_rating: 4.12,
    synopsis:
      'In the aftermath of the battle of Golyn Niis, Rin is stranded, broken, and alone. She\'s lost everything—her home, her mentor, her people. The Republican forces offer her a chance to join their cause and fight the Mugenese Empire. But as Rin discovers what the Republic really wants from her, she must decide how far she\'ll go in pursuit of vengeance.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'Grimdark', 'Dark Fantasy'],
    tropes: ['Political Intrigue', 'Revenge Story', 'Betrayal', 'Coming of Age'],
    magic_system: 'Soft Magic',
    tone: ['Grimdark', 'Dark & Serious', 'Action-packed'],
    pacing: 'Mixed',
    heat_level: 'Clean',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: 'Half a King',
    slug: 'half-a-king',
    authors: ['Joe Abercrombie'],
    isbn: '9780804178457',
    cover_url: cover('9780804178457'),
    publication_year: 2014,
    page_count: 358,
    avg_rating: 3.88,
    synopsis:
      'Prince Yarvi, second-born and half-handed, has no interest in ruling. But when his father and brother are murdered, he is thrust onto the throne—then betrayed into slavery. His path to freedom and revenge will teach him that to win you must be willing to use every tool at your disposal.',
    audience: 'Young Adult (YA)',
    subgenres: ['Epic Fantasy', 'Grimdark'],
    tropes: ['Betrayal', 'Revenge Story', 'Coming of Age', 'Political Intrigue'],
    magic_system: 'No Magic',
    tone: ['Dark & Serious', 'Action-packed', 'Grimdark'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: ['Disability Rep'],
  },
  {
    title: 'The Lions of Al-Rassan',
    slug: 'the-lions-of-al-rassan',
    authors: ['Guy Gavriel Kay'],
    isbn: '9780060733490',
    cover_url: cover('9780060733490'),
    publication_year: 1995,
    page_count: 528,
    avg_rating: 4.37,
    synopsis:
      'In a world mirroring medieval Spain, three people from different faiths become bound together by friendship and love: a celebrated soldier, a physician-poet, and a mercenary captain. Their fates collide as the wars of religion that will define their world bear down upon them. A masterwork of historical fantasy about love, loyalty, and the cost of civilization.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy'],
    tropes: ['Forbidden Romance', 'Political Intrigue', 'Betrayal', 'War Between Kingdoms'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Dark & Serious', 'Philosophical'],
    pacing: 'Slow-burn',
    heat_level: 'Steamy',
    diversity_rep: [],
  },
  {
    title: 'Jade City',
    slug: 'jade-city',
    authors: ['Fonda Lee'],
    isbn: '9780316440974',
    cover_url: cover('9780316440974'),
    publication_year: 2017,
    page_count: 560,
    avg_rating: 4.23,
    synopsis:
      'On the island of Kekon, jade is a magical resource that gives warriors enhanced speed, strength, and perception. Two rival clans—the No Peak and the Mountain—have controlled jade for generations. When a new drug threatens to democratize jade\'s power, an old feud erupts into all-out war.',
    audience: 'Adult',
    subgenres: ['Urban Fantasy', 'Epic Fantasy'],
    tropes: ['Political Intrigue', 'Betrayal', 'Found Family', 'War Between Kingdoms'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Action-packed', 'Atmospheric'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: 'She Who Became the Sun',
    slug: 'she-who-became-the-sun',
    authors: ['Shelley Parker-Chan'],
    isbn: '9781250621801',
    cover_url: cover('9781250621801'),
    publication_year: 2021,
    page_count: 428,
    avg_rating: 4.02,
    synopsis:
      'In a famine-stricken village in 14th-century China, a girl disguises herself as her dead brother to claim his fate—greatness—and survive. Masquerading as a monk, she must rise through the ranks of a rebellion against the Mongol-ruled Yuan dynasty to become the person destiny intended her brother to be.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'Grimdark'],
    tropes: ['Secret Identity', 'Political Intrigue', 'Coming of Age', 'Forbidden Romance'],
    magic_system: 'No Magic',
    tone: ['Dark & Serious', 'Grimdark', 'Atmospheric'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: ['POC Protagonist', 'LGBTQ+ Protagonist'],
  },
  {
    title: 'Senlin Ascends',
    slug: 'senlin-ascends',
    authors: ['Josiah Bancroft'],
    isbn: '9781682392478',
    cover_url: cover('9781682392478'),
    publication_year: 2013,
    page_count: 336,
    avg_rating: 4.18,
    synopsis:
      'The Tower of Babel is the greatest marvel in the world. Headmaster Thomas Senlin travels to it on his honeymoon with his wife—and loses her in the crowd before they even enter. To find her, he must ascend the Tower level by level, each ringdom stranger and more dangerous than the last.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'Steampunk Fantasy'],
    tropes: ['Quest', 'Reluctant Hero', 'Found Family'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Dark & Serious', 'Whimsical'],
    pacing: 'Fast-paced',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'The Ocean at the End of the Lane',
    slug: 'the-ocean-at-the-end-of-the-lane',
    authors: ['Neil Gaiman'],
    isbn: '9780062255655',
    cover_url: cover('9780062255655'),
    publication_year: 2013,
    page_count: 181,
    avg_rating: 4.00,
    synopsis:
      'A middle-aged man returns to his childhood home and remembers an extraordinary event from when he was seven years old. He befriended a girl at the end of his lane whose family kept something ancient and unknowable in their pond. A meditation on memory, childhood, and the unknowable forces that shape our lives.',
    audience: 'Adult',
    subgenres: ['Contemporary Fantasy', 'Dark Fantasy'],
    tropes: ['Coming of Age'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Dark & Serious', 'Philosophical'],
    pacing: 'Slow-burn',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'Warbreaker',
    slug: 'warbreaker',
    authors: ['Brandon Sanderson'],
    isbn: '9780765360038',
    cover_url: cover('9780765360038'),
    publication_year: 2009,
    page_count: 592,
    avg_rating: 4.13,
    synopsis:
      'Two sisters—Vivenna and Siri—are princesses of Idris, a kingdom at the edge of war with Hallandren. When plans change, sheltered Siri is sent to marry the God King of Hallandren instead of her prepared sister. Both women become entangled in a world of gods, magic, and political machinations beyond their understanding.',
    audience: 'Adult',
    subgenres: ['High Fantasy', 'Epic Fantasy'],
    tropes: ['Enemies to Lovers', 'Political Intrigue', 'Forbidden Romance', 'Secret Identity'],
    magic_system: 'Hard Magic',
    tone: ['Dark & Serious', 'Humorous', 'Action-packed'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Daughter of the Moon Goddess',
    slug: 'daughter-of-the-moon-goddess',
    authors: ['Sue Lynn Tan'],
    isbn: '9780063031807',
    cover_url: cover('9780063031807'),
    publication_year: 2022,
    page_count: 477,
    avg_rating: 4.05,
    synopsis:
      'When Xingyin\'s mother is discovered to have illegally taken the elixir of immortality, Xingyin is forced to flee their home on the moon. Seeking safety in the Celestial Kingdom, she conceals her identity and trains as a soldier—all while searching for the rare ingredients that can free her mother from her imprisonment.',
    audience: 'Adult',
    subgenres: ['Mythic Fantasy', 'Historical Fantasy', 'Romantic Fantasy'],
    tropes: ['Quest', 'Forbidden Romance', 'Chosen One', 'Coming of Age'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Hopeful', 'Character-driven'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: ['POC Protagonist'],
  },
  {
    title: "The Witch's Heart",
    slug: 'the-witchs-heart',
    authors: ['Genevieve Gornichec'],
    isbn: '9781984806987',
    cover_url: cover('9781984806987'),
    publication_year: 2021,
    page_count: 368,
    avg_rating: 3.84,
    synopsis:
      'Angrboda\'s story begins where most legends end: with a punishment. Odin burns her three times and she keeps coming back. She retreats to the farthest edge of the world, where she meets Loki and begins a family. But fate has a way of catching up, even with a witch who has been forgotten by the gods.',
    audience: 'Adult',
    subgenres: ['Mythic Fantasy', 'Historical Fantasy'],
    tropes: ['Forbidden Romance', 'Slow Burn', 'Coming of Age'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Dark & Serious', 'Character-driven'],
    pacing: 'Slow-burn',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'The Once and Future Witches',
    slug: 'the-once-and-future-witches',
    authors: ['Alix E. Harrow'],
    isbn: '9780316422031',
    cover_url: cover('9780316422031'),
    publication_year: 2020,
    page_count: 517,
    avg_rating: 4.00,
    synopsis:
      'In 1893, the three Eastwood sisters reunite in the city of New Salem. Juniper is a wild-hearted radical; Agnes is a factory worker pregnant with a secret; Beatrice is a scholar with a dangerous past. Together, they discover that witchcraft and women\'s suffrage are more connected than the world wants to admit.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'Contemporary Fantasy'],
    tropes: ['Found Family', 'Political Intrigue', 'Coming of Age'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Hopeful', 'Character-driven'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: ['LGBTQ+ Side Characters'],
  },
  {
    title: 'The Traitor Baru Cormorant',
    slug: 'the-traitor-baru-cormorant',
    authors: ['Seth Dickinson'],
    isbn: '9780765380722',
    cover_url: cover('9780765380722'),
    publication_year: 2015,
    page_count: 399,
    avg_rating: 3.90,
    synopsis:
      'The Empire of Masks has swallowed Baru Cormorant\'s home, erased her father, and sent her to a distant country to serve as an Imperial Accountant. Baru has a plan: she will climb to a position of power in the Empire and use that power to destroy it. But the Imperial system is far more clever than she anticipated—and far more seductive.',
    audience: 'Adult',
    subgenres: ['Epic Fantasy', 'Political Fantasy'],
    tropes: ['Political Intrigue', 'Betrayal', 'Secret Identity', 'Revenge Story'],
    magic_system: 'No Magic',
    tone: ['Dark & Serious', 'Philosophical', 'Grimdark'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: ['LGBTQ+ Protagonist', 'POC Protagonist'],
  },
  {
    title: 'The Way of Shadows',
    slug: 'the-way-of-shadows',
    authors: ['Brent Weeks'],
    isbn: '9780316033671',
    cover_url: cover('9780316033671'),
    publication_year: 2008,
    page_count: 645,
    avg_rating: 4.18,
    synopsis:
      'Azoth is a street urchin surviving in the slums of the city of Cenaria. He dreams of apprenticing to Durzo Blint, the city\'s most legendary assassin. To gain that apprenticeship, he must complete an impossible task—and in doing so, begin a journey that will cost him everything he cares about.',
    audience: 'Adult',
    subgenres: ['Dark Fantasy', 'Grimdark', 'Epic Fantasy'],
    tropes: ['Coming of Age', 'Mentor Figure', 'Anti-Hero', 'Political Intrigue'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Grimdark', 'Action-packed'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'A Desolation Called Peace',
    slug: 'a-desolation-called-peace',
    authors: ['Arkady Martine'],
    isbn: '9781250186447',
    cover_url: cover('9781250186447'),
    publication_year: 2021,
    page_count: 496,
    avg_rating: 4.18,
    synopsis:
      'Fleet Captain Three Seagrass sends her former partner Mahit Dzmare a message from the front lines of a war against an alien species. Together they must determine what the aliens actually are—and whether first contact might be possible—before the empire decides to simply destroy them.',
    audience: 'Adult',
    subgenres: ['Science Fantasy', 'Political Fantasy'],
    tropes: ['Found Family', 'Political Intrigue', 'Forbidden Romance'],
    magic_system: 'No Magic',
    tone: ['Atmospheric', 'Philosophical', 'Dark & Serious'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: ['LGBTQ+ Protagonist', 'POC Protagonist'],
  },
  {
    title: 'A Master of Djinn',
    slug: 'a-master-of-djinn',
    authors: ['P. Djèlí Clark'],
    isbn: '9781250267689',
    cover_url: cover('9781250267689'),
    publication_year: 2021,
    page_count: 352,
    avg_rating: 3.97,
    synopsis:
      'Cairo, 1912. Since a mysterious man opened the way to the djinn world fifty years ago, Egypt has become a magical hub. Agent Fatma el-Sha\'arawi of the Ministry of Alchemy, Enchantments and Supernatural Entities investigates a case involving a secret brotherhood claiming to be the returned al-Jahiz—and discovers a conspiracy that could tear both worlds apart.',
    audience: 'Adult',
    subgenres: ['Historical Fantasy', 'Urban Fantasy'],
    tropes: ['Quest', 'Political Intrigue', 'Secret Identity'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Action-packed', 'Atmospheric'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: ['POC Protagonist', 'LGBTQ+ Protagonist'],
  },
  {
    title: 'Skyward',
    slug: 'skyward',
    authors: ['Brandon Sanderson'],
    isbn: '9781984800992',
    cover_url: cover('9781984800992'),
    publication_year: 2018,
    page_count: 513,
    avg_rating: 4.24,
    synopsis:
      'Spensa\'s father was a pilot who fled combat—a coward, people say. That word has haunted her. Now she wants to be a pilot more than anything, and her chance comes when she stumbles upon a long-buried alien starship. To earn her wings she must fight in the skies—and confront the truth about her father.',
    audience: 'Young Adult (YA)',
    subgenres: ['Science Fantasy'],
    tropes: ['Chosen One', 'Coming of Age', 'Reluctant Hero'],
    magic_system: 'No Magic',
    tone: ['Action-packed', 'Hopeful', 'Character-driven'],
    pacing: 'Fast-paced',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'The Silmarillion',
    slug: 'the-silmarillion',
    authors: ['J.R.R. Tolkien'],
    isbn: '9780618391110',
    cover_url: cover('9780618391110'),
    publication_year: 1977,
    page_count: 365,
    avg_rating: 3.89,
    synopsis:
      'The Silmarillion is the history of the Elder Days—the First Age of the World—before the events of The Hobbit and The Lord of the Rings. It tells of the creation of the world, the wars of the Elves against Morgoth, the first Dark Lord, and the forging of the Silmarils—jewels of divine light at the center of the great conflicts.',
    audience: 'Adult',
    subgenres: ['High Fantasy', 'Epic Fantasy', 'Mythic Fantasy'],
    tropes: ['Dark Lord', 'Quest', 'Political Intrigue', 'War Between Kingdoms'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Philosophical', 'Dark & Serious'],
    pacing: 'Mixed',
    heat_level: 'Clean',
    diversity_rep: [],
  },
  {
    title: 'The Once and Future King',
    slug: 'the-once-and-future-king',
    authors: ['T.H. White'],
    isbn: '9780441627400',
    cover_url: cover('9780441627400'),
    publication_year: 1958,
    page_count: 639,
    avg_rating: 4.10,
    synopsis:
      'The story of King Arthur as it has never been told before—beginning with the young Wart, who is educated by Merlyn the magician, and growing into an epic saga of love, war, and the dream of Camelot. White\'s retelling of the Arthurian legend is suffused with wit, sorrow, and a profound meditation on might versus right.',
    audience: 'Adult',
    subgenres: ['High Fantasy', 'Mythic Fantasy'],
    tropes: ['Chosen One', 'Political Intrigue', 'Coming of Age', 'Forbidden Romance'],
    magic_system: 'Soft Magic',
    tone: ['Whimsical', 'Philosophical', 'Dark & Serious'],
    pacing: 'Mixed',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Daughter of the Forest',
    slug: 'daughter-of-the-forest',
    authors: ['Juliet Marillier'],
    isbn: '9780765342843',
    cover_url: cover('9780765342843'),
    publication_year: 1999,
    page_count: 492,
    avg_rating: 4.22,
    synopsis:
      'Sorcha is the youngest child and only daughter of Lord Colum of Sevenwaters. Her six beloved brothers are bewitched into the forms of swans. To rescue them, Sorcha must complete an impossible task—a task that binds her to silence while she faces exile, captivity, and a forbidden love that could destroy everything.',
    audience: 'Adult',
    subgenres: ['Mythic Fantasy', 'Historical Fantasy', 'Romantic Fantasy'],
    tropes: ['Forbidden Romance', 'Quest', 'Curse Breaking', 'Coming of Age'],
    magic_system: 'Soft Magic',
    tone: ['Atmospheric', 'Dark & Serious', 'Character-driven'],
    pacing: 'Slow-burn',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Kingdom of the Wicked',
    slug: 'kingdom-of-the-wicked',
    authors: ['Kerri Maniscalco'],
    isbn: '9780316428477',
    cover_url: cover('9780316428477'),
    publication_year: 2020,
    page_count: 368,
    avg_rating: 3.98,
    synopsis:
      'Sicily, 1899. Emilia and her twin sister Vittoria practice the family\'s secret magic. When Vittoria is found murdered, Emilia summons a demon to help her seek revenge. The demon who answers is Wrath—one of the seven Princes of Hell—and he is not what she expected at all.',
    audience: 'Young Adult (YA)',
    subgenres: ['Historical Fantasy', 'Dark Fantasy', 'Romantic Fantasy'],
    tropes: ['Enemies to Lovers', 'Forbidden Romance', 'Revenge Story', 'Quest'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Atmospheric', 'Action-packed'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
  {
    title: 'Ink and Bone',
    slug: 'ink-and-bone',
    authors: ['Rachel Caine'],
    isbn: '9780451472397',
    cover_url: cover('9780451472397'),
    publication_year: 2015,
    page_count: 352,
    avg_rating: 3.93,
    synopsis:
      'In an alternate history, the Great Library of Alexandria survived. It controls all knowledge and books are strictly regulated—ownership is illegal. Jess Brightwell has grown up in the shadow of this power, working as a book smuggler for his family. When he gets the rare chance to study at the Library itself, he discovers that its benevolent face hides something dark.',
    audience: 'Young Adult (YA)',
    subgenres: ['Historical Fantasy', 'Dark Fantasy'],
    tropes: ['Political Intrigue', 'Coming of Age', 'Found Family', 'Forbidden Romance'],
    magic_system: 'Soft Magic',
    tone: ['Dark & Serious', 'Action-packed', 'Atmospheric'],
    pacing: 'Fast-paced',
    heat_level: 'Fade to Black',
    diversity_rep: [],
  },
];

async function seed() {
  console.log('🌱 Seeding fantasy books with full metadata...\n');

  let inserted = 0;
  let failed = 0;

  for (const book of BOOKS) {
    process.stdout.write(`📖 "${book.title}"... `);

    const { error } = await supabase.from('books').upsert(book, { onConflict: 'slug' });

    if (error) {
      console.log(`❌ ${error.message}`);
      failed++;
    } else {
      console.log('✅');
      inserted++;
    }
  }

  console.log(`\n✨ Done! ${inserted} inserted, ${failed} failed.`);
}

seed().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
