/**
 * Maps our category slugs and branding keys to their optimized image paths.
 * Images are generated by: npm run images:optimize
 * Source files live in: assets/raw/
 */

/** Returns a WebP srcset string for a category image (400w and 800w). */
export function categorySrcset(slug: CategorySlug, format: 'webp' | 'avif' = 'webp'): string {
  const base = `/images/categories/${slug}`;
  return `${base}-400.${format} 400w, ${base}-800.${format} 800w`;
}

/** Returns the 800px WebP fallback src for a category image. */
export function categoryFallback(slug: CategorySlug): string {
  return `/images/categories/${slug}-800.webp`;
}

export type CategorySlug =
  | 'epic'
  | 'romantasy'
  | 'dark'
  | 'grimdark'
  | 'historical'
  | 'academy'
  | 'folklore'
  | 'cozy'
  | 'progression'
  | 'science'
  | 'sword'
  | 'urban';

/** Maps URL category slugs (from /categories/[slug]) to our image file slug. */
export const CATEGORY_IMAGE_SLUG: Record<string, CategorySlug> = {
  'epic':       'epic',
  'romantasy':  'romantasy',
  'dark':       'dark',
  'grimdark':   'grimdark',
  'historical': 'historical',
  'academy':    'academy',
  'mythology':  'folklore',
  'cozy':       'cozy',
  'litrpg':     'progression',
  'science':    'science',
  'swords':     'sword',
  'urban':      'urban',
};
