/**
 * Maps our category slugs and branding keys to their optimized image paths.
 * Images are generated by: npm run images:optimize
 * Source files live in: assets/raw/
 */

/** Returns a WebP srcset string for a category image (400w and 800w). */
export function categorySrcset(slug: CategorySlug, format: 'webp' | 'avif' = 'webp'): string {
  const base = `/images/categories/${slug}`;
  return `${base}-400.${format} 400w, ${base}-800.${format} 800w`;
}

/** Returns the 800px WebP fallback src for a category image. */
export function categoryFallback(slug: CategorySlug): string {
  return `/images/categories/${slug}-800.webp`;
}

export type CategorySlug =
  | 'epic'
  | 'romantasy'
  | 'dark'
  | 'grimdark'
  | 'historical'
  | 'academy'
  | 'folklore'
  | 'cozy'
  | 'progression'
  | 'science'
  | 'sword'
  | 'urban';

// ── Reading Order Images ──────────────────────────────────────────────────────

export type ReadingOrderImageSlug =
  | 'cosmere'
  | 'stormlight'
  | 'first-law'
  | 'malazan'
  | 'wheel-of-time'
  | 'asoiaf'
  | 'witcher'
  | 'discworld'
  | 'kingkiller'
  | 'robin-hobb'
  | 'black-company'
  | 'kate-daniels'
  | 'acotar'
  | 'throne-of-glass'
  | 'blood-and-ash'
  | 'empyrean'
  | 'drizzt'
  | 'dragonlance'
  | 'divergent'
  | 'memory-sorrow-thorn'
  | 'dresden-files'
  | 'pern'
  | 'grishaverse'
  | 'inheritance-cycle'
  | 'mistborn'
  | 'shannara'
  | 'valdemar'
  | 'earthsea'
  | 'mark-lawrence'
  | 'sarah-j-maas'
  | 'dune'
  | 'middle-earth'
  | 'riordanverse'
  | 'old-kingdom'
  | 'green-bone-saga'
  | 'horus-heresy'
  | 'dungeon-crawler-carl'
  | 'gentleman-bastard'
  | 'john-gwynne'
  | 'caraval'
  | 'cradle'
  | 'locked-tomb'
  | 'narnia'
  | 'dark-tower'
  | 'red-rising'
  | 'book-of-the-new-sun'
  | 'shadows-of-the-apt';

/** Returns a srcset string for a reading-order hero image (400w and 800w). */
export function readingOrderSrcset(slug: ReadingOrderImageSlug, format: 'webp' | 'avif' = 'webp'): string {
  const base = `/images/reading-orders/${slug}`;
  return `${base}-400.${format} 400w, ${base}-800.${format} 800w`;
}

/** Returns the 800px WebP fallback src for a reading-order hero image. */
export function readingOrderFallback(slug: ReadingOrderImageSlug): string {
  return `/images/reading-orders/${slug}-800.webp`;
}

/** Maps reading-order URL slugs to their image file slug. */
export const READING_ORDER_IMAGE_SLUG: Record<string, ReadingOrderImageSlug> = {
  'cosmere':       'cosmere',
  'stormlight':    'stormlight',
  'first-law':     'first-law',
  'malazan':       'malazan',
  'wheel-of-time': 'wheel-of-time',
  'asoiaf':        'asoiaf',
  'witcher':       'witcher',
  'discworld':     'discworld',
  'kingkiller':    'kingkiller',
  'robin-hobb':    'robin-hobb',
  'black-company':        'black-company',
  'kate-daniels':         'kate-daniels',
  'acotar':               'acotar',
  'throne-of-glass':      'throne-of-glass',
  'blood-and-ash':        'blood-and-ash',
  'empyrean':             'empyrean',
  'drizzt':               'drizzt',
  'dragonlance':          'dragonlance',
  'divergent':            'divergent',
  'memory-sorrow-thorn':  'memory-sorrow-thorn',
  'dresden-files':        'dresden-files',
  'pern':                 'pern',
  'grishaverse':          'grishaverse',
  'inheritance-cycle':    'inheritance-cycle',
  'mistborn':             'mistborn',
  'shannara':             'shannara',
  'valdemar':             'valdemar',
  'earthsea':             'earthsea',
  'mark-lawrence':        'mark-lawrence',
  'sarah-j-maas':         'sarah-j-maas',
  'dune':                 'dune',
  'middle-earth':         'middle-earth',
  'rick-riordan':         'riordanverse',
  'old-kingdom':          'old-kingdom',
  'green-bone-saga':      'green-bone-saga',
  'horus-heresy':         'horus-heresy',
  'dungeon-crawler-carl': 'dungeon-crawler-carl',
  'gentleman-bastard':    'gentleman-bastard',
  'john-gwynne':          'john-gwynne',
  'caraval':              'caraval',
  'cradle':               'cradle',
  'locked-tomb':          'locked-tomb',
  'narnia':               'narnia',
  'dark-tower':           'dark-tower',
  'red-rising':           'red-rising',
  'gene-wolfe':           'book-of-the-new-sun',
  'shadows-of-the-apt':  'shadows-of-the-apt',
};

// ── Category Images ───────────────────────────────────────────────────────────

/** Maps URL category slugs (from /categories/[slug]) to our image file slug. */
export const CATEGORY_IMAGE_SLUG: Record<string, CategorySlug> = {
  'epic':       'epic',
  'romantasy':  'romantasy',
  'dark':       'dark',
  'grimdark':   'grimdark',
  'historical': 'historical',
  'academia':    'academy',
  'mythology':  'folklore',
  'cozy':       'cozy',
  'litrpg':     'progression',
  'science-fantasy': 'science',
  'swords':     'sword',
  'urban':      'urban',
};
